# 使用 .env* 管理不同環境的設定檔。
# 詳情請參考 https://medium.com/@mehdi_hosseini/how-to-link-multiple-docker-compose-files-7250f10063a9。
# 所以根據各個環境去設定有變化的部份，不變的部份則放在這個檔案裡面。
# By Arvin Yang - 2023/12/13

version: '3.8'

include:
  - path: ./.docker/build.${BUILD_ENV}.yml
    project_directory: .

x-params:
  TZ: &tz Asia/Taipei
  TZ_OFFSET: &tz_offset 28800  # 8*60*60

x-postgres: &pg_dsn
  # 用內建的 schema，不用自己建
  POSTGRES_DB: &pg_db postgres
  # postgres 的使用者不能用 pg_*
  POSTGRES_USER: &pg_user chat_user
  POSTGRES_PASSWORD: &pg_pwd 9}!fbW3P>4+j9ZN&Uv^2x4Pb

services:
  database:
    container_name: db
    build:
      context: ./database
    restart: always
    init: true  # 掛載 tini，讓程式可以正確關閉
    networks:
      my_chat_net:
        ipv4_address: 172.13.0.2
    ports:
      - 5433:5432
    environment:
      <<: *pg_dsn
      TZ: *tz
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my_chat_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.13.0.0/16
          gateway: 172.13.0.1