name: Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.9.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          package_json_file: web/package.json
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.json'

      - name: Install dependencies
        run: pnpm install

      - name: PNPM Lint
        run: pnpm lint

      - name: PNPM Format
        run: pnpm format

      - name: Lint by Lint-Staged
        run: pnpm dlx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
